# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('Maths', 'Mathematics'), ('Phy', 'Physics'), ('Chem', 'Chemistry'), ('Bio', 'Biology')], max_length=5, null=True),
        ),
    ]
